name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pdal~=2.3
  - python-pdal
  - gdal
  - pip~=22.3.1
  - pip:
    - lazperf==1.4.4
    - laspy[lazrs,laszip]
    - numpy==1.23.0
