name: venv
channels:
  - conda-forge
  - defaults
  - mathieu
dependencies:
  - python>=3.8
  - pdal>=2.3
  - python-pdal
  - gdal
  - pip
  - lazperf
  - laspy>=2.2.0
  - laszip>=3.4.1
  - lazrs-python>=0.4.3
