name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - gcc
  - pdal
  - gdal
  - python-pdal
#  - pip
#  - pip:
#    - lazperf==1.4.4
#    - laspy[lazrs,laszip]
#    - numpy==1.23.0