name: Docker Image CI cron

on:
  push:
  schedule:
    - cron: '0 0 3 * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build image
      run: |
        docker build . --file Dockerfile -t pdal

    - name: Build test container
      run: |
        docker build . --file Dockerfile-test -t pdal-test
        docker run pdal-test /bin/bash -c "source /venv/bin/activate; python test_laserchicken.py"