name: Build Docker Image

on:
  schedule:
    - cron: '0 0 3 * *'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to github Registry
      uses: docker/login-action@v1
      with:
        registry: "https://index.docker.io/v1/"
    - name: Build container
      run: |
        docker build . --file Dockerfile
